<div class="cool-style-album col-xs-6 col-sm-6 col-lg-4" id="album_<?php echo $wo['album']['id'];?>">
	<div class="wow_content album_parent">
		<div class="avatar">
			<a href="<?php echo $wo['album']['url'];?>" data-ajax="?link1=post&id=<?php echo $wo['album']['id'];?>">
				<?php if ($wo['album']['blur'] == 1) { ?>
					<img src="<?php echo $wo['album']['first_image'];?>" alt="<?php echo $wo['album']['first_image']; ?> Picture" class="image_blur"/>
		      	<?php }else{ ?>
		      		<img src="<?php echo $wo['album']['first_image'];?>" alt="<?php echo $wo['album']['first_image']; ?> Picture" />
		      	<?php } ?>
			</a>
		</div>
		<div class="album-name">
			<a href="<?php echo $wo['album']['url'];?>" data-ajax="?link1=post&id=<?php echo $wo['album']['id'];?>"><h4><?php echo $wo['album']['album_name']; ?></h4></a>
			<a href="<?php echo $wo['album']['url'];?>" data-ajax="?link1=post&id=<?php echo $wo['album']['id'];?>"><p><?php echo Wo_CountAlbumImages($wo['album']['id']);?> <?php echo $wo['lang']['photos']; ?></p></a>
		</div>
	</div>
</div>