<div class="modal fade" id="AI-post-modal" role="dialog">
	<div class="modal-dialog modal-md wow_mat_mdl">
		<form method="post">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
					<h4 class="modal-title"><?php echo $wo['lang']['generate_ai_post']; ?></h4>
				</div>
				<div class="modal-body" style="padding:0;">
					<div class="ai_generate_post_alert"></div>
					<?php if ($wo['config']['text_credit_system'] == 1 && $wo['config']['generated_word_price'] > 0) { ?>
					<div class="alert alert-warning">
						<p id="creditTT"><?php echo(str_replace('{credit}', getAvailableWordBalance(), $wo['lang']['available_words_credits'])) ?></p>
					</div>
					<?php } ?>
					<div class="wow_form_fields">
						<textarea dir="auto" rows="5" name="text" id="aiPostText"></textarea>
					</div>
					<div class="wow_form_fields">
						<input type="number" name="count" max="<?php echo($wo['config']['maxCharacters']); ?>" placeholder="<?php echo $wo['lang']['max_result_length']; ?>" id="aiPostCount" oninput="checkMaxAllowedPostWords(this)">
					</div>
					<div class="wow_form_fields">
						<textarea dir="auto" rows="5" name="text" id="generatedAiPostText" placeholder="<?php echo $wo['lang']['generated_post']; ?>" readonly></textarea>
					</div>
			    <input type="hidden" name="user" value="<?php echo $wo['user']['user_id'];?>">
				</div>
				<div class="modal-footer" style="border: none">
					<div class="ball-pulse"><div></div><div></div><div></div></div>
					<?php if ($wo['config']['text_credit_system'] == 1 && $wo['config']['generated_word_price'] > 0) { ?>
					<button type="button" class="btn main btn-mat" id="buy-ai-image-button" onclick="openAICredit('AI-post-modal')"><?php echo $wo['lang']['buy_credit']; ?></button>
					<?php } ?>
					<button type="button" class="btn main btn-mat" id="ai-generate-post-button" onclick="openAIPost()"><?php echo $wo['lang']['generate']; ?></button>
				</div>
			</div>
		</form>
	</div>
</div>
<script type="text/javascript">
	function checkMaxAllowedPostWords(self) {
		let max = parseInt("<?php echo($wo['config']['maxCharacters']); ?>");
		<?php if ($wo['config']['text_credit_system'] == 1 && $wo['config']['generated_word_price'] > 0) { ?>
			let paid = parseInt(parseInt($('#current_user_credits').val()) / parseInt("<?php echo($wo['config']['generated_word_price']) ?>"));
			if (paid < max) {
				max = paid;
			}
		<?php } ?>

		if (parseInt($(self).val()) > max) {
			$(self).val(max);
			$(self).attr('max',max);
		}
	}
	function openAIPost() {
		$("#ai-generate-post-button").text("<?php echo($wo['lang']['please_wait']) ?>");
		$("#ai-generate-post-button").attr('disabled',true);
		$('#ai-selected-post-button').remove();
		$.post(Wo_Ajax_Requests_File()+'?f=ai&s=openai_post', {text: $('#aiPostText').val(),count: $('#aiPostCount').val()}, function(data, textStatus, xhr) {
			if (data.status == 200) {
				<?php if ($wo['config']['text_credit_system'] == 1 && $wo['config']['generated_word_price'] > 0) { ?>
					$('#current_user_credits').val(data.credits);
					var text = "<?php echo($wo['lang']['available_words_credits']); ?>";
					$('#creditTT').text(text.replace("{credit}", getAvailableByType('text')));
					checkMaxAllowedPostWords('#aiPostCount');
				<?php } ?>

				$("#ai-generate-post-button").text("<?php echo $wo['lang']['generate']; ?>");
				$("#ai-generate-post-button").removeAttr('disabled');
				$('#generatedAiPostText').val(data.output);
				$("#AI-post-modal .modal-footer").prepend('<button type="button" class="btn main btn-mat" id="ai-selected-post-button" onclick="addAIPost()"><?php echo $wo['lang']['select']; ?></button>');
			}
			else{
				$("#ai-generate-post-button").removeAttr('disabled');
				$("#ai-generate-post-button").text("<?php echo($wo['lang']['generate']) ?>");
		    	$('.ai_generate_post_alert').html('<div class="alert alert-danger">' + data.message + '</div>');
		    	setTimeout(() => {
			  		$('.ai_generate_post_alert').html('');
			  	},3000);
			}
		});
	}

	function addAIPost() {
		$('#post-textarea .postText').val($('#generatedAiPostText').val());
		$('#AI-post-modal').modal('hide');
		$('#postSticker').val('');
		$('#ai-selected-post-button').remove();
		$('#AI-post-modal textarea').val('');
	}
	function openPostModel() {
		$("#ai-generate-post-button").removeAttr('disabled');
		$('.ai_generate_post_alert').html("");
		<?php if ($wo['config']['text_credit_system'] == 1 && $wo['config']['generated_word_price'] > 0) { ?>
			var text = "<?php echo($wo['lang']['available_words_credits']); ?>";
			$('#creditTT').text(text.replace("{credit}", getAvailableByType('text')));
			if ($('#current_user_credits').val() < <?php echo($wo['config']['generated_word_price']) ?>) {
				$('#ai-generate-post-button').attr('disabled',true);
				$('.ai_generate_post_alert').html("<div class='alert alert-danger'><?php echo $wo["lang"]["you_dont_have_enough_credits"]?></div>");
			}
		<?php } ?>
		$('#AI-post-modal').modal('show');
	}
</script>