<div class="modal fade" id="AI-user-modal" role="dialog">
	<div class="modal-dialog modal-md wow_mat_mdl">
		<form method="post">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
					<h4 class="modal-title"><?php echo $wo['lang']['convert_avatar_image']; ?></h4>
				</div>
				<div class="modal-body" style="padding:0;">
					<?php if ($wo['config']['images_credit_system'] == 1 && $wo['config']['generated_image_price'] > 0) { ?>
					<div class="alert alert-warning">
						<p id="creditTU"><?php echo(str_replace('{credit}', getAvailableImageBalance(), $wo['lang']['available_images_credits'])) ?></p>
					</div>
					<?php } ?>
					<div class="ai_user_alert"></div>
					<div class="wow_form_fields">
						<textarea placeholder="<?php echo $wo['lang']['enter_prompt']?>" dir="auto" rows="5" name="text" id="aiUserText"></textarea>
					</div>
					<div id="productimage-holder">
					</div>
			    <input type="hidden" name="user" value="<?php echo $wo['user']['user_id'];?>">
			    <input type="hidden" value="avatar" id="ai-user-model-type">
				</div>
				<div class="modal-footer" style="border: none">
					<div class="ball-pulse"><div></div><div></div><div></div></div>
					<?php if ($wo['config']['images_credit_system'] == 1 && $wo['config']['generated_image_price'] > 0) { ?>
					<button type="button" class="btn main btn-mat" id="buy-ai-image-button" onclick="openAICredit('AI-user-modal')"><?php echo $wo['lang']['buy_credit']; ?></button>
					<?php } ?>
					<button type="button" class="btn main btn-mat" id="ai-user-button" onclick="generateUserImages()"><?php echo $wo['lang']['generate']; ?></button>
				</div>
			</div>
		</form>
	</div>
</div>
<script type="text/javascript">
	var aiUserImage = [];
	function addAIUserImages(type = 'avatar') {
		$('#AI-user-modal').modal('hide');
		if (type == 'avatar') {
			$('.profile_avatar input')[0].files = new FileListItems(aiUserImage);
			Wo_UpdateProfileAvatar();
		}
		else{
			$('.profile_cover input')[0].files = new FileListItems(aiUserImage);
			Wo_UpdateProfileCover();
		}
		$("#AI-user-modal #productimage-holder").html('');
		$('#ai-selected-user-button').remove();
		$('#aiUserText').val('');
		aiUserImage = [];
	}
	function checkAIUser(id,type = 'avatar') {
		$.post(Wo_Ajax_Requests_File()+'?f=ai&s=check', {id: id}, function(data, textStatus, xhr) {
			if (data.status == 200) {
				if (data.output == null) {
					$("#ai-user-button").text(data.status_text);
				}
				else{
					clearInterval(window.checkAI);
					<?php if ($wo['config']['images_credit_system'] == 1 && $wo['config']['generated_image_price'] > 0) { ?>
						$('#current_user_credits').val(data.credits);
						var text = "<?php echo($wo['lang']['available_images_credits']); ?>";
						$('#creditTU').text(text.replace("{credit}", getAvailableByType('image')));
					<?php } ?>
					
					$("#ai-user-button").text("<?php echo($wo['lang']['generate']) ?>");
					$("#ai-user-button").removeAttr('disabled');
					
					var ii = 0;
					for (var i = 0; i < data.output.length; i++) {
						loadImageFromUrl(data.output[i]).then(async dataUrl => {
					     var fileData = await imageDataToFile(dataUrl, "Ai_image_"+ii+".jpg");
					     aiUserImage.push(fileData);
					     name = "'"+data.output[ii]+"'";
						$("#AI-user-modal #productimage-holder").append('<span class="thumb-image-delete" id="image_to_'+ii+'" data-href="'+dataUrl+'" onclick="Wo_OpenLighteBox(this,event);"><img src="'+dataUrl+'" class="thumb-image"></span>')
					     
					     if (ii == data.output.length - 1) {
					     	$("#AI-user-modal .modal-footer").prepend(`<button type="button" class="btn main btn-mat" id="ai-selected-user-button" onclick="addAIUserImages('${type}')"><?php echo $wo['lang']['select']; ?></button>`);
					     }
					     ii = ii + 1;
					   })
					}

					$('#generatedAiPostText').val(data.output);
				}
			}
			else{
				$("#ai-user-button").text("<?php echo($wo['lang']['generate']) ?>");
				$("#ai-user-button").removeAttr('disabled');
		    	$('.ai_user_alert').html('<div class="alert alert-danger">' + data.message + '</div>');
		    	setTimeout(() => {
			  		$('.ai_user_alert').html('');
			  	},3000);
			  	clearInterval(window.checkAI);
			}
		});
	}
	function generateUserImages(type = 'avatar') {
		clearInterval(window.checkAI);
		$("#AI-user-modal #productimage-holder").html('');
		$('#ai-selected-user-button').remove();
		$("#ai-user-button").text("<?php echo($wo['lang']['please_wait']) ?>");
		$("#ai-user-button").attr("disabled","true");
		$('#ai-selected-user-button').remove();
		$.post(Wo_Ajax_Requests_File()+'?f=ai&s=convert', {text: $('#aiUserText').val(),type: type}, function(data, textStatus, xhr) {
			if (data.status == 200) {
				$("#ai-user-button").text(data.status_text);
				window.checkAI = setInterval(() => {checkAIUser(data.id,type)} , 3000);
			}
			else{
				$("#ai-user-button").removeAttr('disabled');
				$("#ai-user-button").text("<?php echo($wo['lang']['generate']) ?>");
		    	$('.ai_user_alert').html('<div class="alert alert-danger">' + data.message + '</div>');
		    	setTimeout(() => {
			  		$('.ai_user_alert').html('');
			  	},3000);
			}
		});
	}
	function openAiUserModel(type = 'avatar') {
		
		$('#ai-user-model-type').val(type);
		$("#ai-user-button").removeAttr('disabled');
		$('.ai_user_alert').html("");
		<?php if ($wo['config']['images_credit_system'] == 1 && $wo['config']['generated_image_price'] > 0) { ?>
			var text = "<?php echo($wo['lang']['available_images_credits']); ?>";
			$('#creditTU').text(text.replace("{credit}", getAvailableByType('image')));
			if ($('#current_user_credits').val() < <?php echo($wo['config']['generated_image_price']) ?>) {
				$('#ai-user-button').attr('disabled',true);
				$('.ai_user_alert').html("<div class='alert alert-danger'><?php echo $wo["lang"]["you_dont_have_enough_credits"]?></div>");
			}
		<?php } ?>
		if (type == 'avatar') {
			$('#AI-user-modal .modal-title').text("<?php echo $wo['lang']['convert_avatar_image']; ?>");
		}
		else{
			$('#AI-user-modal .modal-title').text("<?php echo $wo['lang']['convert_cover_image']; ?>");
		}
		$('#ai-user-button').attr('onclick',`generateUserImages("${type}")`);
		$("#AI-user-modal #productimage-holder").html('');
		$('#ai-selected-user-button').remove();
		$('#aiUserText').val('');
		aiUserImage = [];
		$('#AI-user-modal').modal('show');
	}
</script>